[package]
name = "part2"
version = "0.1.0"
edition = "2024"

[dependencies]
console_log = "1.0.0"
leptos = { version = "0.8.14", features = ["csr"] }
reqwasm = "0.5.0"
reqwest = { version = "0.12.25", features = ["json"] }
serde = "1.0.228"
thiserror = "2.0.17"
web-sys = "0.3.83"
